package fr.vinarnt.animu.finder.compose.model

enum class AnimeGenre(val id: Int) {
    ACTION(1),
    ADVENTURE(2),
    COMEDY(4),
    AVANT_GARDE(5),
    MYSTERY(7),
    DRAMA(8),
    ECCHI(9),
    FANTASY(10),
    GAME(11),
    HISTORICAL(13),
    HORROR(14),
    MARTIAL_ARTS(17),
    MECHA(18),
    MUSIC(19),
    PARODY(20),
    ROMANCE(22),
    SCHOOL(23),
    SCI_FI(24),
    SPACE(29),
    SPORTS(30),
    SUPER_POWER(31),
    VAMPIRE(32),
    HAREM(35),
    SLICE_OF_LIFE(36),
    SUPERNATURAL(37),
    MILITARY(38),
    POLICE(39),
    PSYCHOLOGICAL(40),
    SUSPENSE(41),
    AWARD_WINNING(46),
    GOURMET(47)
}